// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfCFZ68tuM4DyeS_S8PA-_IxxEKDn-dhQ',
    appId: '1:94649893814:web:172f88e30221db98b1b717',
    messagingSenderId: '94649893814',
    projectId: 'jibsul2',
    authDomain: 'jibsul2.firebaseapp.com',
    databaseURL: 'https://jibsul2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jibsul2.appspot.com',
    measurementId: 'G-0NHHJ9FNWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn3I3amXXyuE0EV4Z1cTJ8haZ9g0V4_Ts',
    appId: '1:94649893814:android:bdd9dcda673cf5f0b1b717',
    messagingSenderId: '94649893814',
    projectId: 'jibsul2',
    databaseURL: 'https://jibsul2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jibsul2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIDQFrLh2pkLraMBOvrylRU0OkEMN7gE0',
    appId: '1:94649893814:ios:4dfc877198c0f279b1b717',
    messagingSenderId: '94649893814',
    projectId: 'jibsul2',
    databaseURL: 'https://jibsul2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jibsul2.appspot.com',
    iosClientId: '94649893814-2pk7og37o7filtohgtms5f0vc3vsmln1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sogra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIDQFrLh2pkLraMBOvrylRU0OkEMN7gE0',
    appId: '1:94649893814:ios:42fa43e67d45c264b1b717',
    messagingSenderId: '94649893814',
    projectId: 'jibsul2',
    databaseURL: 'https://jibsul2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jibsul2.appspot.com',
    iosClientId: '94649893814-lsov2ncfd3afvs5jiefn8j2gij0svvpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sogra.RunnerTests',
  );
}
